In [37]:
import  numpy as np


def matrix_multiply(A, B):
    """
    param: A
    type: n1 by m matrix, n1,m > 1
    param: B
    type: m by n2 matrix, n2, m > 1
    return: C matrix, n1 by n2
    """
    A_row, A_colum = A.shape
    B_row, B_colum = B.shape
    C = np.zeros((A_row, B_colum))
    for i in xrange(A_row):
        for j in xrange(B_colum):
            c_ij = 0
            for k in xrange(A_colum):
                c_ij = c_ij + A[i,k] * B[k, j]
            C[i,j] = c_ij
    print("The matrix multiply C: {0}".format(C))
    
    
def square_matrix_multiply_recursive(A, B):
    """
    param: A
    type: n by n matrix, n is the power of 2
    param: B 
    type: n by n matrix, n is the power of 2
    return: C
    type: n by n matrix
    """
    A_row = A.shape[0]
    b_row = B.shape[0]
    if A_row != b_row:
        raise
    
    n = A_row
    if n == 1:
        C = A * B
    else:
        C11 = square_matrix_multiply_recursive(A[:n/2,:n/2], B[:n/2,:n/2]) + \
                square_matrix_multiply_recursive(A[:n/2,n/2:], B[n/2:,:n/2])
        C12 = square_matrix_multiply_recursive(A[:n/2,:n/2],B[:n/2,n/2:]) + \
                square_matrix_multiply_recursive(A[:n/2,:n/2],B[n/2:,n/2:])
        C21 = square_matrix_multiply_recursive(A[n/2:,:n/2],B[:n/2,:n/2]) + \
                square_matrix_multiply_recursive(A[n/2:,n/2:],B[n/2:,:n/2])
        C22 = square_matrix_multiply_recursive(A[n/2:,:n/2],B[:n/2,n/2:]) + \
                square_matrix_multiply_recursive(A[n/2:,n/2:],B[n/2:,n/2:])
        C = np.zeros(A.shape)
        C[:n/2, :n/2] = C11
        C[:n/2, n/2:] = C12
        C[n/2:, :n/2] = C21
        C[n/2:, n/2:] = C12  
#     print("The matrix multiply rescursive C: {0}".format(C))
    return C


In [38]:
A = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])
B = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1,1, 1]])
matrix_multiply(A, B)
C = square_matrix_multiply_recursive(A, B)
print("The matrix multiply rescursive C: {0}".format(C))

The matrix multiply C: [[ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]]
The matrix multiply rescursive C: [[ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]]
